Add playlist tbl
scp756-221/term-project-k8sound pull request #38
Opened 2022-03-10 05:00 UTC by HardysJin

2022-03-10 05:06 UTC, HardysJin commented
Finish issues:
- [] #36 
- [] #26 
- [] #14 
- [] #15

2022-03-10 06:50 UTC, KamiCreed commented
Why did you copy the CI playlist code to your `dev` folder? Is there no way to use the tests in `ci` directly?

2022-03-11 09:03 UTC, HardysJin commented
Only create api is finished, why we have CI test implemented first before we done all APIs?

2022-03-11 09:20 UTC, KamiCreed commented
A more recent build I did should comment out some tests to allow the build to pass. Those tests can be re-added back in or one can implement new tests for when the API is implemented.

2022-03-11 09:25 UTC, KamiCreed commented
Oh, wait. What. You already implemented the create playlist in here? And it also seems like you did your own version of CI in the dev folder... This kind of stuff seems like should be communicated to us, but Ok I see.

2022-03-11 09:47 UTC, KamiCreed commented
Also, is this a completed PR? I saw the checklist and thought possibly they were not finished, so I set this PR as a draft. If it is, I'll review it fully tomorrow.

By the way, if you want this PR to automatically close issues you should write it as such "Finish/Closes #<num>" as shown in a tutorial.

2022-03-11 17:33 UTC, HardysJin commented
> Oh, wait. What. You already implemented the create playlist in here? And it also seems like you did your own version of CI in the dev folder... This kind of stuff seems like should be communicated to us, but Ok I see.

Yea, I have no way to check the content for the newly created playlist until the **read** api is done. Didn't want to remove the CI test function for playlist, but it fails as I added **create** api. Working on fixing it.

2022-03-11 17:36 UTC, KamiCreed commented
Be sure to pull in changes from the main branch before editing it too much, since I've changed it recently in a previous PR I believe.

2022-03-11 23:11 UTC, KamiCreed requested changes
Mostly good. I've also identified why the tests were failing, and I also wonder why the CI files seems to be repeated in your `dev` folder.

2022-03-11 23:11 UTC, KamiCreed commented on s3/app.py
> +    return (response.json())
I think you may need to return the entire response instead of just the JSON, since in my `ci/v1.1/playlist.py`, it tries to extract the `.status_code`. Also, you might need to edit the return function to remove the JSON return, since the creation shouldn't return the entry probably.

2022-03-11 23:11 UTC, KamiCreed commented on dev/test/playlist.py
> +"""
This file looks like a copy of the CI. Is there a reason for repeating it here?

2022-03-11 23:11 UTC, KamiCreed commented on ci/v1.1/create_tables.py
> +class DB_Manager:
This is a good refactoring for creating the tables.

2022-03-12 20:55 UTC, HardysJin commented on s3/app.py
> +    return (response.json())
Fixed. Create playlist api needs two args - **user_id** and **music_ids**

2022-03-12 20:56 UTC, HardysJin commented on dev/test/playlist.py
> +"""
Just my personal preference when i start my local dev, it runs some automated tests first.

2022-03-12 21:45 UTC, KamiCreed commented on dev/test/playlist.py
> +"""
Hm? But you can run the automated tests locally as well with the `runci-local.sh`...

2022-03-12 22:02 UTC, KamiCreed approved these changes

2022-03-13 00:38 UTC, merged